version: "3.8"

networks:
  produtos-api-net:
    name: produtos-api-net
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: produtos-api-mysql
    restart: "no"
    ports: 
      - 3306:3306
    environment:       
      - MYSQL_DATABASE=produtos
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT= 3306    
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 5s
      timeout: 10s
      retries: 20
    networks:
      - produtos-api-net

